import type { Order, PriceBreakdown } from '../types'

// ── Helpers ───────────────────────────────────────────────────────────────────

function wpg(base: number, dist: number, size: number, fragile: number, tip = 0): PriceBreakdown {
  const distanceFee   = dist
  const sizeFee       = size
  const fragileFee    = fragile
  const subtotalPreTax = parseFloat((base + distanceFee + sizeFee + fragileFee).toFixed(2))
  const gst           = parseFloat((subtotalPreTax * 0.05).toFixed(2))
  const pst           = parseFloat((subtotalPreTax * 0.07).toFixed(2))
  const totalTax      = parseFloat((gst + pst).toFixed(2))
  const subtotalWithTax = parseFloat((subtotalPreTax + totalTax).toFixed(2))
  return {
    baseFee: base, distanceFee, sizeFee, fragileFee,
    subtotalPreTax, gst, pst, hst: 0, qst: 0,
    totalTax, subtotalWithTax, tip, total: parseFloat((subtotalWithTax + tip).toFixed(2)),
  }
}

function ts(hoursAgo: number): string {
  return new Date(Date.now() - hoursAgo * 3_600_000).toISOString()
}

// ── Orders ────────────────────────────────────────────────────────────────────

export const MOCK_ORDERS: Order[] = [
  // ── Delivered (8) ───────────────────────────────────────────────────────────
  {
    id: 'CS-3001', customerId: 'u1', customerName: 'Sasha Novak',
    pickup:  { name: 'Sasha Novak',    phone: '204 555 0199', address: '134 Princess St, Exchange District' },
    dropoff: { name: 'Mei Tanaka',     phone: '204 555 0148', address: '88 Osborne St, Osborne Village' },
    parcel: { size: 'm', desc: 'Clothing parcels', fragile: false },
    status: 'delivered', assignedDriverId: 'd1', assignedDriverName: 'Armen Petrossian',
    priceBreakdown: wpg(14, 0, 2, 0, 3),
    cityId: 'winnipeg', distanceKm: 4.2,
    createdAt: ts(26), updatedAt: ts(24),
    notes: [],
  },
  {
    id: 'CS-3002', customerId: 'u3', customerName: 'Carlos Rivera',
    pickup:  { name: 'Carlos Rivera',  phone: '204 555 0132', address: '1455 Portage Ave, St. James' },
    dropoff: { name: 'Emma Wilson',    phone: '204 555 0143', address: '2200 McPhillips St, North End' },
    parcel: { size: 'l', desc: 'Electronics box', fragile: true },
    status: 'delivered', assignedDriverId: 'd4', assignedDriverName: 'Marcus Williams',
    priceBreakdown: wpg(14, 3.50, 4, 2, 5),
    cityId: 'winnipeg', distanceKm: 12,
    createdAt: ts(30), updatedAt: ts(28),
    notes: [{ id: 'n1', text: 'Customer requested extra care with the box.', authorName: 'Admin', createdAt: ts(29) }],
  },
  {
    id: 'CS-3003', customerId: 'u4', customerName: 'Aiko Patel',
    pickup:  { name: 'Aiko Patel',     phone: '204 555 0117', address: '799 Pembina Hwy, Fort Rouge' },
    dropoff: { name: 'James Thompson', phone: '204 555 0165', address: '55 Garry St, Downtown' },
    parcel: { size: 's', desc: 'Documents envelope', fragile: false },
    status: 'delivered', assignedDriverId: 'd2', assignedDriverName: 'Dmitri Volkov',
    priceBreakdown: wpg(14, 0, 0, 0, 2),
    cityId: 'winnipeg', distanceKm: 3.1,
    createdAt: ts(22), updatedAt: ts(20),
    notes: [],
  },
  {
    id: 'CS-3004', customerId: 'u11', customerName: 'Ryan O\'Connor',
    pickup:  { name: 'Ryan O\'Connor', phone: '204 555 0134', address: '1020 Henderson Hwy, East Kildonan' },
    dropoff: { name: 'Zoe Laurent',    phone: '204 555 0168', address: '445 Broadway Ave, Fort Rouge' },
    parcel: { size: 'm', desc: 'Gift box', fragile: false },
    status: 'delivered', assignedDriverId: 'd3', assignedDriverName: 'Sofia Chen',
    priceBreakdown: wpg(14, 1.75, 2, 0, 0),
    cityId: 'winnipeg', distanceKm: 11,
    createdAt: ts(18), updatedAt: ts(16),
    notes: [],
  },
  {
    id: 'CS-3005', customerId: 'u13', customerName: 'Lucas Mendez',
    pickup:  { name: 'Lucas Mendez',   phone: '204 555 0191', address: '234 Main St, North End' },
    dropoff: { name: 'Ava Johnson',    phone: '204 555 0147', address: '1234 St. Mary\'s Rd, St. Vital' },
    parcel: { size: 'l', desc: 'Moving boxes (2)', fragile: false },
    status: 'delivered', assignedDriverId: 'd5', assignedDriverName: 'Priya Sharma',
    priceBreakdown: wpg(14, 0, 4, 0, 4),
    cityId: 'winnipeg', distanceKm: 7.8,
    createdAt: ts(14), updatedAt: ts(12),
    notes: [],
  },
  {
    id: 'CS-3006', customerId: 'u7', customerName: 'Liam Chen',
    pickup:  { name: 'Liam Chen',      phone: '204 555 0176', address: '672 Notre Dame Ave, Industrial' },
    dropoff: { name: 'Oliver Brown',   phone: '204 555 0113', address: '888 Dakota St, St. Vital' },
    parcel: { size: 's', desc: 'USB drive + paperwork', fragile: false },
    status: 'delivered', assignedDriverId: 'd7', assignedDriverName: 'Yuki Tanaka',
    priceBreakdown: wpg(14, 0, 0, 0, 0),
    cityId: 'winnipeg', distanceKm: 5.5,
    createdAt: ts(10), updatedAt: ts(8),
    notes: [],
  },
  {
    id: 'CS-3007', customerId: 'u8', customerName: 'Sophie Martin',
    pickup:  { name: 'Sophie Martin',  phone: '204 555 0154', address: '388 Donald St, Downtown' },
    dropoff: { name: 'David Kim',      phone: '204 555 0189', address: '2500 Portage Ave, Westwood' },
    parcel: { size: 'm', desc: 'Fragile artwork', fragile: true },
    status: 'delivered', assignedDriverId: 'd8', assignedDriverName: 'Amara Diallo',
    priceBreakdown: wpg(14, 1.75, 2, 2, 3),
    cityId: 'winnipeg', distanceKm: 11,
    createdAt: ts(36), updatedAt: ts(34),
    notes: [],
  },
  {
    id: 'CS-3008', customerId: 'u9', customerName: 'David Kim',
    pickup:  { name: 'David Kim',      phone: '204 555 0189', address: '101 Vaughan St, The Forks' },
    dropoff: { name: 'Sasha Novak',    phone: '204 555 0199', address: '799 Pembina Hwy, Fort Rouge' },
    parcel: { size: 's', desc: 'Sample kit', fragile: false },
    status: 'delivered', assignedDriverId: 'd1', assignedDriverName: 'Armen Petrossian',
    priceBreakdown: wpg(14, 0, 0, 0, 2),
    cityId: 'winnipeg', distanceKm: 2.8,
    createdAt: ts(48), updatedAt: ts(46),
    notes: [],
  },

  // ── In Transit (4) ──────────────────────────────────────────────────────────
  {
    id: 'CS-3009', customerId: 'u10', customerName: 'Priya Singh',
    pickup:  { name: 'Priya Singh',    phone: '204 555 0122', address: '88 Osborne St, Osborne Village' },
    dropoff: { name: 'Carlos Rivera',  phone: '204 555 0132', address: '134 Princess St, Exchange District' },
    parcel: { size: 'm', desc: 'Legal documents', fragile: false },
    status: 'in_transit', assignedDriverId: 'd1', assignedDriverName: 'Armen Petrossian',
    priceBreakdown: wpg(14, 1.75, 2, 0),
    cityId: 'winnipeg', distanceKm: 11,
    createdAt: ts(1.5), updatedAt: ts(0.5),
    notes: [],
  },
  {
    id: 'CS-3010', customerId: 'u5', customerName: 'James Thompson',
    pickup:  { name: 'James Thompson', phone: '204 555 0165', address: '445 Broadway Ave, Fort Rouge' },
    dropoff: { name: 'Aiko Patel',     phone: '204 555 0117', address: '55 Garry St, Downtown' },
    parcel: { size: 'l', desc: 'Server equipment', fragile: true },
    status: 'in_transit', assignedDriverId: 'd4', assignedDriverName: 'Marcus Williams',
    priceBreakdown: wpg(14, 0, 4, 2),
    cityId: 'winnipeg', distanceKm: 4.2,
    createdAt: ts(2), updatedAt: ts(0.8),
    notes: [],
  },
  {
    id: 'CS-3011', customerId: 'u2', customerName: 'Mei Tanaka',
    pickup:  { name: 'Mei Tanaka',     phone: '204 555 0148', address: '2200 McPhillips St, North End' },
    dropoff: { name: 'Ryan O\'Connor', phone: '204 555 0134', address: '388 Donald St, Downtown' },
    parcel: { size: 'm', desc: 'Baked goods', fragile: true },
    status: 'in_transit', assignedDriverId: 'd8', assignedDriverName: 'Amara Diallo',
    priceBreakdown: wpg(14, 0, 2, 2),
    cityId: 'winnipeg', distanceKm: 6.3,
    createdAt: ts(1.2), updatedAt: ts(0.3),
    notes: [],
  },
  {
    id: 'CS-3012', customerId: 'u12', customerName: 'Zoe Laurent',
    pickup:  { name: 'Zoe Laurent',    phone: '204 555 0168', address: '55 Garry St, Downtown' },
    dropoff: { name: 'Priya Singh',    phone: '204 555 0122', address: '1234 St. Mary\'s Rd, St. Vital' },
    parcel: { size: 's', desc: 'Keys + paperwork', fragile: false },
    status: 'in_transit', assignedDriverId: 'd3', assignedDriverName: 'Sofia Chen',
    priceBreakdown: wpg(14, 0, 0, 0),
    cityId: 'winnipeg', distanceKm: 5.9,
    createdAt: ts(0.9), updatedAt: ts(0.2),
    notes: [],
  },

  // ── Picked Up (3) ───────────────────────────────────────────────────────────
  {
    id: 'CS-3013', customerId: 'u15', customerName: 'Oliver Brown',
    pickup:  { name: 'Oliver Brown',   phone: '204 555 0113', address: '2500 Portage Ave, Westwood' },
    dropoff: { name: 'Lucas Mendez',   phone: '204 555 0191', address: '234 Main St, North End' },
    parcel: { size: 'm', desc: 'Clothing returns', fragile: false },
    status: 'picked_up', assignedDriverId: 'd3', assignedDriverName: 'Sofia Chen',
    priceBreakdown: wpg(14, 3.50, 2, 0),
    cityId: 'winnipeg', distanceKm: 12,
    createdAt: ts(0.7), updatedAt: ts(0.1),
    notes: [],
  },
  {
    id: 'CS-3014', customerId: 'u8', customerName: 'Sophie Martin',
    pickup:  { name: 'Sophie Martin',  phone: '204 555 0154', address: '672 Notre Dame Ave, Industrial' },
    dropoff: { name: 'David Kim',      phone: '204 555 0189', address: '888 Dakota St, St. Vital' },
    parcel: { size: 'l', desc: 'Printer + cables', fragile: false },
    status: 'picked_up', assignedDriverId: 'd4', assignedDriverName: 'Marcus Williams',
    priceBreakdown: wpg(14, 0, 4, 0),
    cityId: 'winnipeg', distanceKm: 8.4,
    createdAt: ts(0.6), updatedAt: ts(0.15),
    notes: [],
  },
  {
    id: 'CS-3015', customerId: 'u14', customerName: 'Ava Johnson',
    pickup:  { name: 'Ava Johnson',    phone: '204 555 0147', address: '1234 St. Mary\'s Rd, St. Vital' },
    dropoff: { name: 'Liam Chen',      phone: '204 555 0176', address: '101 Vaughan St, The Forks' },
    parcel: { size: 's', desc: 'Birthday card + gift', fragile: false },
    status: 'picked_up', assignedDriverId: 'd8', assignedDriverName: 'Amara Diallo',
    priceBreakdown: wpg(14, 0, 0, 0),
    cityId: 'winnipeg', distanceKm: 6.1,
    createdAt: ts(0.5), updatedAt: ts(0.05),
    notes: [],
  },

  // ── Assigned (3) ────────────────────────────────────────────────────────────
  {
    id: 'CS-3016', customerId: 'u1', customerName: 'Sasha Novak',
    pickup:  { name: 'Sasha Novak',    phone: '204 555 0199', address: '134 Princess St, Exchange District' },
    dropoff: { name: 'Emma Wilson',    phone: '204 555 0143', address: '799 Pembina Hwy, Fort Rouge' },
    parcel: { size: 'm', desc: 'Sample products', fragile: false },
    status: 'assigned', assignedDriverId: 'd2', assignedDriverName: 'Dmitri Volkov',
    priceBreakdown: wpg(14, 0, 2, 0),
    cityId: 'winnipeg', distanceKm: 3.5,
    createdAt: ts(0.3), updatedAt: ts(0.05),
    notes: [],
  },
  {
    id: 'CS-3017', customerId: 'u5', customerName: 'James Thompson',
    pickup:  { name: 'James Thompson', phone: '204 555 0165', address: '1455 Portage Ave, St. James' },
    dropoff: { name: 'Carlos Rivera',  phone: '204 555 0132', address: '2200 McPhillips St, North End' },
    parcel: { size: 'l', desc: 'Camera gear', fragile: true },
    status: 'assigned', assignedDriverId: 'd5', assignedDriverName: 'Priya Sharma',
    priceBreakdown: wpg(14, 3.50, 4, 2),
    cityId: 'winnipeg', distanceKm: 12,
    createdAt: ts(0.25), updatedAt: ts(0.04),
    notes: [],
  },
  {
    id: 'CS-3018', customerId: 'u4', customerName: 'Aiko Patel',
    pickup:  { name: 'Aiko Patel',     phone: '204 555 0117', address: '799 Pembina Hwy, Fort Rouge' },
    dropoff: { name: 'Mei Tanaka',     phone: '204 555 0148', address: '88 Osborne St, Osborne Village' },
    parcel: { size: 'm', desc: 'Books', fragile: false },
    status: 'assigned', assignedDriverId: 'd7', assignedDriverName: 'Yuki Tanaka',
    priceBreakdown: wpg(14, 0, 2, 0),
    cityId: 'winnipeg', distanceKm: 1.8,
    createdAt: ts(0.2), updatedAt: ts(0.03),
    notes: [],
  },

  // ── New (4) ─────────────────────────────────────────────────────────────────
  {
    id: 'CS-3019', customerId: 'u11', customerName: 'Ryan O\'Connor',
    pickup:  { name: 'Ryan O\'Connor', phone: '204 555 0134', address: '1020 Henderson Hwy, East Kildonan' },
    dropoff: { name: 'Oliver Brown',   phone: '204 555 0113', address: '888 Dakota St, St. Vital' },
    parcel: { size: 's', desc: 'Medication', fragile: false },
    status: 'new',
    priceBreakdown: wpg(14, 0, 0, 0),
    cityId: 'winnipeg', distanceKm: 9.2,
    createdAt: ts(0.1), updatedAt: ts(0.1),
    notes: [],
  },
  {
    id: 'CS-3020', customerId: 'u10', customerName: 'Priya Singh',
    pickup:  { name: 'Priya Singh',    phone: '204 555 0122', address: '234 Main St, North End' },
    dropoff: { name: 'Sophie Martin',  phone: '204 555 0154', address: '445 Broadway Ave, Fort Rouge' },
    parcel: { size: 'm', desc: 'Work files', fragile: false },
    status: 'new',
    priceBreakdown: wpg(14, 1.75, 2, 0),
    cityId: 'winnipeg', distanceKm: 11,
    createdAt: ts(0.05), updatedAt: ts(0.05),
    notes: [],
  },
  {
    id: 'CS-3021', customerId: 'u9', customerName: 'David Kim',
    pickup:  { name: 'David Kim',      phone: '204 555 0189', address: '388 Donald St, Downtown' },
    dropoff: { name: 'Zoe Laurent',    phone: '204 555 0168', address: '55 Garry St, Downtown' },
    parcel: { size: 'l', desc: 'Marketing materials', fragile: false },
    status: 'new',
    priceBreakdown: wpg(14, 0, 4, 0),
    cityId: 'winnipeg', distanceKm: 0.8,
    createdAt: ts(0.02), updatedAt: ts(0.02),
    notes: [],
  },
  {
    id: 'CS-3022', customerId: 'u13', customerName: 'Lucas Mendez',
    pickup:  { name: 'Lucas Mendez',   phone: '204 555 0191', address: '888 Dakota St, St. Vital' },
    dropoff: { name: 'Ava Johnson',    phone: '204 555 0147', address: '672 Notre Dame Ave, Industrial' },
    parcel: { size: 's', desc: 'Phone charger', fragile: false },
    status: 'new',
    priceBreakdown: wpg(14, 0, 0, 0),
    cityId: 'winnipeg', distanceKm: 7.1,
    createdAt: ts(0.01), updatedAt: ts(0.01),
    notes: [],
  },

  // ── Demo driver orders (d0 — driver@citysend.ca) ────────────────────────────
  {
    id: 'CS-3026', customerId: 'u6', customerName: 'Emma Wilson',
    pickup:  { name: 'Emma Wilson',    phone: '204 555 0143', address: '388 Donald St, Downtown',            note: 'Buzz unit 402' },
    dropoff: { name: 'Sasha Novak',    phone: '204 555 0199', address: '134 Princess St, Exchange District', note: 'Leave at front desk' },
    parcel: { size: 'm', desc: 'Framed photo — handle with care', fragile: true },
    status: 'assigned', assignedDriverId: 'd0', assignedDriverName: 'Demo Driver',
    priceBreakdown: wpg(14, 0, 2, 2, 3),
    cityId: 'winnipeg', distanceKm: 3.2,
    createdAt: ts(0.4), updatedAt: ts(0.1),
    notes: [{ id: 'n_demo1', text: 'Fragile item — customer requested careful handling.', authorName: 'Admin', createdAt: ts(0.35) }],
  },
  {
    id: 'CS-3027', customerId: 'u3', customerName: 'Carlos Rivera',
    pickup:  { name: 'Carlos Rivera',  phone: '204 555 0132', address: '1455 Portage Ave, St. James' },
    dropoff: { name: 'Priya Singh',    phone: '204 555 0122', address: '88 Osborne St, Osborne Village',    note: 'Ring doorbell twice' },
    parcel: { size: 'l', desc: 'Laptop + charger', fragile: false },
    status: 'in_transit', assignedDriverId: 'd0', assignedDriverName: 'Demo Driver',
    priceBreakdown: wpg(14, 3.50, 4, 0, 5),
    cityId: 'winnipeg', distanceKm: 12,
    createdAt: ts(1.5), updatedAt: ts(0.3),
    notes: [],
  },
  {
    id: 'CS-3028', customerId: 'u9', customerName: 'David Kim',
    pickup:  { name: 'David Kim',      phone: '204 555 0189', address: '101 Vaughan St, The Forks' },
    dropoff: { name: 'Zoe Laurent',    phone: '204 555 0168', address: '672 Notre Dame Ave, Industrial' },
    parcel: { size: 's', desc: 'USB drives (x3)', fragile: false },
    status: 'delivered', assignedDriverId: 'd0', assignedDriverName: 'Demo Driver',
    priceBreakdown: wpg(14, 0, 0, 0, 2),
    cityId: 'winnipeg', distanceKm: 4.1,
    createdAt: ts(5), updatedAt: ts(4),
    notes: [],
  },

  // ── Cancelled (3) ───────────────────────────────────────────────────────────
  {
    id: 'CS-3023', customerId: 'u3', customerName: 'Carlos Rivera',
    pickup:  { name: 'Carlos Rivera',  phone: '204 555 0132', address: '2500 Portage Ave, Westwood' },
    dropoff: { name: 'James Thompson', phone: '204 555 0165', address: '1455 Portage Ave, St. James' },
    parcel: { size: 'm', desc: 'Laptop sleeve', fragile: false },
    status: 'cancelled', cancelReason: 'Customer requested cancellation before pickup.',
    priceBreakdown: wpg(14, 0, 2, 0),
    cityId: 'winnipeg', distanceKm: 2.1,
    createdAt: ts(72), updatedAt: ts(71),
    notes: [],
  },
  {
    id: 'CS-3024', customerId: 'u6', customerName: 'Emma Wilson',
    pickup:  { name: 'Emma Wilson',    phone: '204 555 0143', address: '101 Vaughan St, The Forks' },
    dropoff: { name: 'Sasha Novak',    phone: '204 555 0199', address: '134 Princess St, Exchange District' },
    parcel: { size: 'l', desc: 'Antique vase', fragile: true },
    status: 'cancelled', cancelReason: 'Item too fragile for standard courier service.',
    priceBreakdown: wpg(14, 0, 4, 2),
    cityId: 'winnipeg', distanceKm: 1.9,
    createdAt: ts(96), updatedAt: ts(95),
    notes: [],
  },
  {
    id: 'CS-3025', customerId: 'u7', customerName: 'Liam Chen',
    pickup:  { name: 'Liam Chen',      phone: '204 555 0176', address: '55 Garry St, Downtown' },
    dropoff: { name: 'Priya Singh',    phone: '204 555 0122', address: '234 Main St, North End' },
    parcel: { size: 'm', desc: 'Notebooks + pens', fragile: false },
    status: 'cancelled', cancelReason: 'Duplicate order — customer resubmitted.',
    priceBreakdown: wpg(14, 0, 2, 0),
    cityId: 'winnipeg', distanceKm: 3.4,
    createdAt: ts(50), updatedAt: ts(49),
    notes: [],
  },
]
